config/routes.rb
Rails.application.routes.draw do
  resources :essays
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/essay.rb
# frozen_string_literal: true

class Essay < ApplicationRecord
  validates :title, presence: true
  has_rich_text :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/essays_controller.rb
# frozen_string_literal: true

class EssaysController < ApplicationController
  def new
    @essay = Essay.new
  end

  def create
    @essay = Essay.new(essay_params)
    if @essay.save
      redirect_to essays_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def show
    @essay = Essay.find(params[:id])
  end

  def index
    @essays = Essay.all
  end

  def destroy
  end

  private

  def essay_params
    params.require(:essay).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/essays/edit.html.erb
<h1>Essays#edit</h1>
<p>Find me in app/views/essays/edit.html.erb</p>

app/views/essays/index.html.erb
<h1>Essays</h1>
<p><%= link_to "New Essay", new_essay_path %></p>
<ul>
  <% @essays.each do |essay| %>
    <li><%= link_to essay.title, essay_path(essay) %></li>
  <% end %>
</ul>

app/views/essays/new.html.erb
<h1>New Essay</h1>
<%= form_with model: @essay do |f| %>
  <%= f.text_field :title %>
  <%= f.rich_text_area :body %>
  <%= f.submit %>
<% end %>

app/views/essays/show.html.erb
<h1><%= @essay.title %></h1>

<%= @essay.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionTextDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>